
project_id = "rtkfehmdemjdslcwaxyi"

[functions.send-contact-email]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.openai-proxy]
verify_jwt = false
